# Generated by Django 3.2.6 on 2021-08-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
