# Generated by Django 3.2.6 on 2021-08-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_positions_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='polyline',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
